name: cd

on:
  push:
    branches:
      - master
      - develop

env: 
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Clone
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::880587150218:oidc-provider
        aws-region: us-east-1

        
    - name: Publish on prod
      if: github.ref == 'refs/heads/master'
      run: ./publish.sh prod

    - name: Publish on dev
      if: github.ref == 'refs/heads/develop'
      run: ./publish.sh dev
